services:
  - type: web
    name: ft-ticket-bot
    env: node
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y wget gnupg && \
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
      sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
      apt-get update && \
      apt-get install -y google-chrome-stable && \
      npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"
