services:
  - type: web
    name: ft-ticket-bot
    env: node
    plan: free
    region: oregon
    buildCommand: bash ./install-chrome.sh && npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
