services:
  - type: web
    name: ft-ticket-bot
    env: node
    plan: free
    buildCommand: npm install && npm install puppeteer
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
